# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               GMOD EvoHack
tagline:             'Supplementary wiki'
description:         'The supplementary (and at first original) wiki content for the <a href="http://gmod.org/wiki/GMOD_Evo_Hackathon" target="_blank">GMOD Tools for Evolutionary Biology Hackathon</a>, a collaboration between <a href="http://nescent.org" target="_blank">NESCent</a> and <a href="http://gmod.org" target="_blank">GMOD</a>.'
url:                 http://nescent.github.io/Tools-for-Evohack
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hackathon participants
  url:               http://gmod.org/wiki/GMOD_Evo_Hackathon
  email:             info@gmod.org

# Custom vars
version:             1.0.0
